/** biome-ignore-all lint/suspicious/noThenProperty: registry keys follow Given/When/Then naming convention; not Promise-like */
/**
 * ATID Registry — Acceptance Test ID → Given/When/Then assertion map.
 *
 * Generated by `spec-writer` (Factivist S1 Phase 1 swarm) on 2026-05-23.
 *
 * Source of truth for human-readable wording: `S1-PRD` wiki page
 *   https://github.com/facktivist/factivist/wiki/S1-PRD
 *
 * Source of truth for traceability: this file. Phase 6 (`qa-lead`) MUST mirror
 * every entry into a vitest/playwright spec whose title contains the ATID.
 * Phase 7 (`ci-eng`) MUST add a CI step that fails if any registry entry has
 * no matching test file.
 *
 * NOTE: This is a registry, not test code. It exports a structured map only.
 * Do not import this into runtime bundles — `__tests__` is excluded from the
 * `packages/shared` build output via tsconfig + vitest config.
 *
 * Memory key: `s1-phase-1-atid-registry`.
 */

export interface AtidEntry {
  /** Feature the ATID belongs to: 'identity' | 'complaint' | 'discovery' | 'moderation' | 'comment' | 'legal' | 'admin' */
  readonly feature:
    | 'identity'
    | 'complaint'
    | 'discovery'
    | 'moderation'
    | 'comment'
    | 'legal'
    | 'admin'
  /** Given clause — system state before the action. */
  readonly given: string
  /** When clause — the action under test. */
  readonly when: string
  /** Then clause — the assertion(s) that MUST hold. */
  readonly then: string
  /** GitHub Project #3 issue URL(s) this ATID gates. */
  readonly issueUrls: readonly string[]
  /** Cross-links: research wiki sections, ADR issues, design surfaces. */
  readonly crossRefs?: readonly string[]
}

export const ATID_REGISTRY: Record<string, AtidEntry> = {
  // ─────────────────────────────────────────────────────────────────────
  // FEATURE 1 — Onboarding + anoncitizen ZKP verification
  // ─────────────────────────────────────────────────────────────────────

  'ATID-IDENT-001': {
    feature: 'identity',
    given: 'a new citizen with a valid UIDAI-signed Aadhaar QR and no prior citizens row',
    when: 'they complete the web onboarding flow and submit a Groth16 proof to POST /identity/verify',
    then: 'CitizenVerifier.sol::verifyAndRecord returns true, a new row is written to citizens with nullifier, state, district, created_at only, the response sets a session cookie scoped to the resulting citizen_id, and no Aadhaar number, name, DOB, photo, or PIN is ever logged, persisted, or transmitted server-side',
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/53',
      'https://github.com/facktivist/factivist/issues/54',
      'https://github.com/facktivist/factivist/issues/56',
    ],
    crossRefs: [
      'wiki:Research-Anoncitizen-ZKP#2-nullifier-formula-canonical-source',
      'ADR-003 #38',
      'ADR-010 #45',
    ],
  },

  'ATID-IDENT-002': {
    feature: 'identity',
    given: 'a citizen whose nullifier is already present in citizens',
    when: 'they attempt a second POST /identity/verify (same Aadhaar, same FACTIVIST_NULLIFIER_SEED_V1)',
    then: "the API responds 409 Conflict with { error: 'nullifier_already_used' }, no new row is written, and the on-chain nullifierUsed[] lookup is the authoritative source (API MUST verify against chain state, not just the local row)",
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/53',
      'https://github.com/facktivist/factivist/issues/56',
    ],
    crossRefs: ['wiki:Research-Anoncitizen-ZKP#2.3-uniqueness-guarantee'],
  },

  'ATID-IDENT-003': {
    feature: 'identity',
    given: 'any successful verification event',
    when: 'an auditor inspects the citizens row, all server logs (Sentry + Cloudflare + Fly.io), and the Supabase audit trail for that request',
    then: 'no field, header, log line, or trace span contains an Aadhaar number, name, gender, DOB, address, photo bytes, PIN code, GPS coordinate, IP address (post-Cloudflare-scrub), or device fingerprint; only nullifier, state, district, created_at, and the request trace_id are recorded',
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/45',
      'https://github.com/facktivist/factivist/issues/70',
    ],
    crossRefs: ['ADR-010 #45', 'ATID-P5C6 #70'],
  },

  'ATID-IDENT-004': {
    feature: 'identity',
    given: 'the mobile app on a device whose class is low-tier (< 4 GB RAM or pre-A12 iPhone)',
    when: 'the user starts ZKP proving',
    then: "the client routes the witness to the server-side prover at POST /identity/prove, downloads only the resulting proof, and submits it to POST /identity/verify, and the device-class decision is logged to dev_metrics.llm_calls (purpose='zkp_route') without any PII",
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/50',
      'https://github.com/facktivist/factivist/issues/55',
    ],
    crossRefs: ['ADR-011 #50', 'wiki:Research-Anoncitizen-ZKP#5-mobile-feasibility'],
  },

  'ATID-IDENT-005': {
    feature: 'identity',
    given: 'a verified citizen',
    when: 'they (or any other user) view /profile/[citizen_id]',
    then: "the page renders only an anonymous handle (deterministically derived from nullifier via Poseidon, no UIDAI data), the citizen's state + district, their complaint count, and join date; no name, no photo, no contact field, no PIN; the handle MUST collide with the same input across web + mobile (deterministic)",
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/29',
      'https://github.com/facktivist/factivist/issues/53',
    ],
    crossRefs: ['ADR-010 #45'],
  },

  'ATID-IDENT-006': {
    feature: 'identity',
    given: 'any citizens.nullifier',
    when: 'the handle is derived in packages/shared/src/handle.ts (Poseidon-based; collision-resistant; ~10 chars base32)',
    then: 'the same input yields the same output across web + mobile (golden-test verified), the function never receives any UIDAI-derived data other than the nullifier, and the resulting handle decodes to a 50-bit value (low collision risk at S1 user scale)',
    issueUrls: ['https://github.com/facktivist/factivist/issues/29'],
  },

  'ATID-IDENT-007': {
    feature: 'identity',
    given: 'the GET /citizens/:handle endpoint',
    when: 'the response is inspected',
    then: 'it contains only { handle, state, district, complaint_count, joined_at } — no name, no nullifier, no citizen_id, no IP, no email, no contact field (verified by JSON schema test)',
    issueUrls: ['https://github.com/facktivist/factivist/issues/53'],
  },

  // ─────────────────────────────────────────────────────────────────────
  // FEATURE 2 — Complaint composer
  // ─────────────────────────────────────────────────────────────────────

  'ATID-COMPL-001': {
    feature: 'complaint',
    given: 'a verified citizen with a valid session',
    when: "they POST /complaints with { body: '...up to 5000 chars...', category_slug, state_code, district_code, pc_code, ac_code, photos: [≤3 multipart files] }",
    then: "the response is 201 Created with the new complaint_id and created_at; a row is written to complaints; each photo is uploaded to Supabase Storage at complaint-photos/<complaint_id>/<n>.jpg (signed-URL only, never public); and the complaints.tsvector column is populated with to_tsvector('english', body || ' ' || title) for FTS",
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/58',
      'https://github.com/facktivist/factivist/issues/60',
      'https://github.com/facktivist/factivist/issues/61',
    ],
  },

  'ATID-COMPL-002': {
    feature: 'complaint',
    given: 'an uploaded photo containing EXIF GPS, device serial, owner name, and orientation tags',
    when: 'the server persists it via Sharp',
    then: 'the stored object MUST be re-encoded JPEG with only the orientation tag preserved; all GPS, device, owner, datetime-original, software, and maker-note tags MUST be absent (verified by exiftool in the test suite)',
    issueUrls: ['https://github.com/facktivist/factivist/issues/62'],
    crossRefs: [
      'wiki:Research-IT-Act-Posture#6-data-localisation--edge-cases-for-complaint-photos',
      'ADR-004 #39',
    ],
  },

  'ATID-COMPL-003': {
    feature: 'complaint',
    given: 'the seeded categories table',
    when: 'the test enumerates rows',
    then: "there are exactly 35 rows, every PK is a stable slug (/^[a-z0-9-]+$/), corruption row exists with severity_flag in (null, 'scandal'), and no row exists for public-money-scandals as a separate category",
    issueUrls: ['https://github.com/facktivist/factivist/issues/51'],
    crossRefs: ['ADR-012 #51'],
  },

  'ATID-COMPL-004': {
    feature: 'complaint',
    given: 'the composer UI',
    when: 'rendered on web or mobile',
    then: "the geolocation input MUST be four cascading dropdowns (state → district → PC → AC), no geolocation API is invoked, no Geolocation.getCurrentPosition exists in the bundle (verified by static check grep -r 'getCurrentPosition' apps/), and the API rejects requests where pc_code does not belong to district_code",
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/52',
      'https://github.com/facktivist/factivist/issues/60',
      'https://github.com/facktivist/factivist/issues/61',
    ],
    crossRefs: ['ADR-013 #52'],
  },

  'ATID-COMPL-005': {
    feature: 'complaint',
    given: 'a request with photos.length > 3 or body.length > 5000',
    when: 'posted',
    then: 'Zod validation rejects with 400 Bad Request and a structured error pointing to the offending field; no row, no storage write',
    issueUrls: ['https://github.com/facktivist/factivist/issues/58'],
  },

  'ATID-COMPL-006': {
    feature: 'complaint',
    given: 'a successful submission',
    when: 'the resulting row is inspected',
    then: 'complaints.author_id references citizens.id only; no field stores the raw nullifier, IP, user-agent, or session cookie value; and the public read API (GET /complaints/:id) returns author_handle (the same Poseidon-derived handle from Feature 1), not author_id',
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/58',
      'https://github.com/facktivist/factivist/issues/45',
    ],
    crossRefs: ['ADR-010 #45'],
  },

  'ATID-COMPL-007': {
    feature: 'complaint',
    given: 'a published complaint',
    when: 'an unauthenticated visitor GET /complaints/:id',
    then: "the response is 200 OK with the complaint body, category, constituency tags, photo signed-URLs (≤ 1h TTL), comment list, flag count, created_at, author_handle, and the disclaimer string 'User-submitted; not verified by Factivist.'; no author_id, nullifier, or IP appears in the response",
    issueUrls: ['https://github.com/facktivist/factivist/issues/58'],
  },

  // ─────────────────────────────────────────────────────────────────────
  // FEATURE 3 — Comments + flagging
  // ─────────────────────────────────────────────────────────────────────

  'ATID-COMMENT-001': {
    feature: 'comment',
    given: 'an unauthenticated visitor',
    when: 'they POST /complaints/:id/comments',
    then: 'the API responds 401 Unauthorized; given a verified citizen, when they post a comment body ≤ 1000 chars, then 201 Created, a row is written to comments with author_id = citizens.id, the public read surface shows author_handle (not author_id), and the comment renders flat (no parent_comment_id field)',
    issueUrls: ['https://github.com/facktivist/factivist/issues/67'],
  },

  'ATID-COMMENT-002': {
    feature: 'comment',
    given: 'a verified citizen viewing a complaint',
    when: "they POST /complaints/:id/flag with { reason: 'defamation'|'communal'|'false'|'doxxing'|'other', note?: string }",
    then: "the response is 204 No Content, a row is written to moderation_queue with status='pending', flagged_by=citizens.id, flagged_at, reason, and the complaint's public flag count increments; the flagging citizen's identity MUST NOT be visible to other users",
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/68',
      'https://github.com/facktivist/factivist/issues/65',
    ],
  },

  // ─────────────────────────────────────────────────────────────────────
  // FEATURE 4 — Discovery (browse + FTS)
  // ─────────────────────────────────────────────────────────────────────

  'ATID-DISC-001': {
    feature: 'discovery',
    given: 'the seeded constituency dataset and ≥ 50 sample complaints distributed across states',
    when: 'a visitor calls GET /complaints?state=KA&district=BLR-U&pc=BLR-S&ac=BTM-LAYOUT&page=1&pageSize=20',
    then: 'the response contains only complaints whose (state, district, pc, ac) exactly match, paginated 20 per page, sorted created_at DESC (no algorithmic ranking — preserves §79(2)(b)), with total_count, page, pageSize, and has_next in the envelope',
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/59',
      'https://github.com/facktivist/factivist/issues/63',
    ],
  },

  'ATID-DISC-002': {
    feature: 'discovery',
    given:
      'a request where district does not belong to state, or pc does not belong to district, or ac does not belong to pc',
    when: 'the API processes it',
    then: "the response is 400 Bad Request with { error: 'invalid_constituency_hierarchy', field: '<offending field>' }",
    issueUrls: ['https://github.com/facktivist/factivist/issues/59'],
  },

  'ATID-DISC-003': {
    feature: 'discovery',
    given:
      'the J&K constituency rows seeded from the 2022 Delimitation Order with geometry_stale=true',
    when: 'the browse UI renders J&K results',
    then: "the UI surfaces a visible 'Boundaries pending DataMeet update' notice and the API response includes meta.geometry_stale=true for those rows",
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/14',
      'https://github.com/facktivist/factivist/issues/63',
    ],
    crossRefs: ['wiki:Research-Constituency-Dataset#1.3-known-gaps--risks'],
  },

  'ATID-DISC-004': {
    feature: 'discovery',
    given: 'the GIN-indexed complaints.tsvector column and a corpus of ≥ 100 complaints',
    when: 'a visitor calls GET /complaints?q=potholes&state=KA',
    then: 'results contain only complaints whose body or title matches the tsvector query (verified via EXPLAIN ANALYZE showing GIN index use), combined with the state filter, ranked by ts_rank_cd then created_at DESC, returning in ≤ 300 ms p95 at S1 volumes (≤ 10k complaints)',
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/59',
      'https://github.com/facktivist/factivist/issues/64',
    ],
    crossRefs: ['ADR-005 #40'],
  },

  'ATID-DISC-005': {
    feature: 'discovery',
    given: "complaints with status='moderation_pending' or status='removed'",
    when: 'any anonymous or citizen user searches',
    then: "those rows never appear in results; only status='published' rows are visible to non-admin requesters (verified by Supabase RLS test)",
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/64',
      'https://github.com/facktivist/factivist/issues/96',
    ],
  },

  // ─────────────────────────────────────────────────────────────────────
  // FEATURE 7 — Moderation queue
  // ─────────────────────────────────────────────────────────────────────

  'ATID-MOD-001': {
    feature: 'moderation',
    given: 'a Supabase auth user without the admin role claim',
    when: 'they call GET /admin/moderation or query moderation_queue directly',
    then: 'the API responds 403 Forbidden and Supabase RLS denies the row read; given an admin-role user, when they call the same endpoint, then they receive paginated pending items',
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/65',
      'https://github.com/facktivist/factivist/issues/66',
      'https://github.com/facktivist/factivist/issues/96',
    ],
  },

  'ATID-MOD-002': {
    feature: 'moderation',
    given: 'a moderator viewing a flagged complaint',
    when: 'they inspect the row, the response payload, and any admin-side log',
    then: "no field reveals the author's Aadhaar number, photo, name, IP, device fingerprint, or raw nullifier; the only author reference is author_handle (the same Poseidon-derived handle visible publicly); the adversarial test in ATID-P5C6 MUST fail-fast on any new column or log line that exposes more",
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/70',
      'https://github.com/facktivist/factivist/issues/77',
    ],
    crossRefs: ['ADR-010 #45'],
  },

  'ATID-MOD-003': {
    feature: 'moderation',
    given: 'a moderator decides remove|keep|escalate on a queued item',
    when: 'they submit the decision',
    then: "the action is appended to moderation_actions with actor_id, target_type, target_id, action, rationale, decided_at; the complaint's status updates atomically (removed or published); and a metric is emitted so the dashboard can flag any item open > 24h for defamation/communal flags (Factivist SLA) and any item open > 36h for actual-knowledge takedown (Rule 3(1)(d) ceiling)",
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/65',
      'https://github.com/facktivist/factivist/issues/66',
    ],
  },

  'ATID-MOD-004': {
    feature: 'moderation',
    given: 'a verified citizen flags a published complaint',
    when: 'the flag fires (ATID-COMMENT-002)',
    then: 'the item appears in GET /admin/moderation?status=pending within 1s, the row carries the flag reason and timestamp, and the public complaint count of flags increments',
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/65',
      'https://github.com/facktivist/factivist/issues/68',
    ],
  },

  // ─────────────────────────────────────────────────────────────────────
  // FEATURE 8 — Legal pages + Rule 3(2) workflow
  // ─────────────────────────────────────────────────────────────────────

  'ATID-LEGAL-001': {
    feature: 'legal',
    given: 'the deployed apps/web',
    when: 'a visitor opens /legal/tos, /legal/privacy, /legal/zkp-explainer, /legal/grievance',
    then: 'all four return 200 OK, are linked from the footer of every page (verified by Playwright crawl), are server-rendered (no client gating), and the ToS page includes the Rule 3(1)(b) prohibited-content list verbatim',
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/31',
      'https://github.com/facktivist/factivist/issues/72',
    ],
    crossRefs: ['wiki:Research-IT-Act-Posture#32-rule-31b-inform-users-of-prohibited-content'],
  },

  'ATID-LEGAL-002': {
    feature: 'legal',
    given: 'the /legal/grievance page with a named Grievance Officer (India address + email)',
    when: 'a complainant submits a grievance via the form POST /grievance',
    then: "the API returns 201 Created with a grievance_id; an acknowledgement email is sent to the complainant within 24 hours (verified by job log); a record is written to grievances with status='acknowledged'; and a visible 'Appeal to GAC' link pointing to https://gac.gov.in/ is rendered on the confirmation page",
    issueUrls: ['https://github.com/facktivist/factivist/issues/71'],
    crossRefs: ['wiki:Research-IT-Act-Posture#37-rule-32-grievance-redressal-the-big-one-for-s1'],
  },

  'ATID-LEGAL-003': {
    feature: 'legal',
    given: 'a grievance acknowledged at time t0',
    when: 'the moderation pipeline runs',
    then: "the system MUST emit an alert if the grievance is undisposed at t0 + 15d; and if the grievance is a 'court order or appropriate-Government-agency notification' (actual-knowledge flag=true), an alert at t0 + 36h instead",
    issueUrls: ['https://github.com/facktivist/factivist/issues/71'],
  },

  'ATID-LEGAL-004': {
    feature: 'legal',
    given: "a grievance flagged category='ncii'",
    when: 'the moderation pipeline runs',
    then: 'the system MUST emit an alert at t0 + 24h if undisposed, and the dashboard surfaces NCII-flagged grievances at the top of the queue',
    issueUrls: ['https://github.com/facktivist/factivist/issues/71'],
  },

  'ATID-LEGAL-005': {
    feature: 'legal',
    given: 'a new citizen at the onboarding consent step',
    when: 'the consent screen renders',
    then: "it presents three separate checkboxes (none pre-checked): (a) 'I agree to the Terms of Service', (b) 'I consent to publishing my complaint and photos publicly', (c) 'I consent to storing my photos for the lifetime of the complaint'; and the system MUST refuse registration unless (a) is ticked",
    issueUrls: ['https://github.com/facktivist/factivist/issues/72'],
    crossRefs: ['wiki:Research-IT-Act-Posture#5-dpdp-act-2023--where-it-bites'],
  },

  'ATID-LEGAL-006': {
    feature: 'legal',
    given: 'any verified citizen whose last_tos_notified_at is older than 365 days',
    when: 'they next sign in',
    then: 'they MUST be shown the ToS + prohibited-content list and asked to re-tick the agreement before any new write succeeds',
    issueUrls: ['https://github.com/facktivist/factivist/issues/72'],
  },

  'ATID-LEGAL-007': {
    feature: 'legal',
    given: 'the CERT-In log pipeline (ATID-P8L2)',
    when: 'the runbook is executed in staging',
    then: 'system logs from apps/api are replicated to an India-region bucket (e.g., Supabase Mumbai or AWS ap-south-1) with a 180-day retention policy enforced via lifecycle rule (verified by automated tag check), and NTP on every app/worker node points to time.nic.in / samay1.nic.in (verified by a synthetic check)',
    issueUrls: ['https://github.com/facktivist/factivist/issues/107'],
    crossRefs: [
      'wiki:Research-IT-Act-Posture#4-cert-in-direction-28-apr-2022--mandatory-log-retention',
    ],
  },

  'ATID-LEGAL-008': {
    feature: 'legal',
    given: 'a simulated security incident (e.g., the synthetic alert in the runbook)',
    when: 'ops follows the runbook',
    then: 'there is a documented step that sends an email to cert-in@cert-in.org.in with the prescribed CERT-In incident report fields within 6 hours of detection, and an audit row is written to legal_incidents',
    issueUrls: ['https://github.com/facktivist/factivist/issues/107'],
  },

  'ATID-LEGAL-009': {
    feature: 'legal',
    given: 'the Grievance Officer receives a §69A blocking order (simulated in test)',
    when: 'the order is recorded',
    then: 'a sealed entry is appended to legal_orders with received_at, actioned_at, order_ref, compliance_window_h, and the action evidence (URL hash); compliance window defaults to 48h unless the order says otherwise',
    issueUrls: ['https://github.com/facktivist/factivist/issues/71'],
  },

  'ATID-LEGAL-010': {
    feature: 'legal',
    given: 'any complaint render (read API or UI)',
    when: 'inspected',
    then: "the literal string 'User-submitted; not verified by Factivist.' appears above the body — verified by Playwright and by an API field complaints.disclaimer",
    issueUrls: ['https://github.com/facktivist/factivist/issues/60'],
  },

  'ATID-LEGAL-011': {
    feature: 'legal',
    given: 'the monthly user-count job',
    when: 'the registered Indian user count crosses 3,000,000',
    then: "an alert fires that opens a 'SSMI readiness' epic on Project #3 (Rule 4 obligations would attach at 5 M)",
    issueUrls: ['https://github.com/facktivist/factivist/issues/107'],
  },

  'ATID-LEGAL-012': {
    feature: 'legal',
    given: 'a complaint tagged to a constituency',
    when: 'the constituency centroid lies within 1 km of a known Survey-of-India negative-list installation (seed list checked into packages/db/data/eci/sensitive.csv)',
    then: 'the complaint enters the moderation queue automatically before publication',
    issueUrls: [
      'https://github.com/facktivist/factivist/issues/65',
      'https://github.com/facktivist/factivist/issues/58',
    ],
    crossRefs: [
      'wiki:Research-IT-Act-Posture#6-data-localisation--edge-cases-for-complaint-photos',
    ],
  },

  'ATID-LEGAL-013': {
    feature: 'legal',
    given: "a flag with reason='defamation'",
    when: 'the moderation queue processes it',
    then: 'the SLA monitor uses a 24-hour target (Factivist house policy — tighter than the Rule 3(1)(d) 36-hour ceiling)',
    issueUrls: ['https://github.com/facktivist/factivist/issues/65'],
  },

  'ATID-LEGAL-014': {
    feature: 'legal',
    given: 'the analytics pipeline',
    when: 'the monthly job runs',
    then: 'it emits a single number to dev_metrics.user_count_monthly with rows { month, count } and posts it on the Ops-S1-Scorecard wiki page',
    issueUrls: ['https://github.com/facktivist/factivist/issues/19'],
  },

  'ATID-LEGAL-015': {
    feature: 'legal',
    given: 'the /legal/grievance page',
    when: 'it renders',
    then: "it lists exactly one Grievance Officer with name, postal address in India, telephone, and @factivist.in email (or equivalent India-routable email); the GAC portal link (https://gac.gov.in/) is visible on the same page; and no SSMI 'Three Officer' content is shown",
    issueUrls: ['https://github.com/facktivist/factivist/issues/71'],
  },

  // ─────────────────────────────────────────────────────────────────────
  // FEATURE 7 — Admin guard (role-based access control)
  // ─────────────────────────────────────────────────────────────────────

  'ATID-ADMIN-001': {
    feature: 'admin',
    given:
      'an admin-only API route guarded by `requireAdmin` (apps/api/src/lib/rbac.ts) and an HTTP request carrying a Supabase JWT in the Authorization header',
    when: 'the JWT either (a) has no `role` claim, (b) carries `role` ≠ "admin", or (c) is a citizen nullifier-bound token with no `role` claim at all',
    then: 'requireAdmin throws / responds 403 Forbidden without enumerating which role would have satisfied the guard (no role-enumeration oracle); the contract is asserted by `apps/api/src/lib/__tests__/rbac.test.ts` which is the authoritative gate even though this ATID is not currently exercised by a per-route Playwright spec',
    issueUrls: ['https://github.com/facktivist/factivist/issues/30'],
    crossRefs: [
      'ADR-010 #45',
      'apps/api/src/lib/rbac.ts',
      'apps/api/src/lib/__tests__/rbac.test.ts',
    ],
  },
} as const

export type AtidKey = keyof typeof ATID_REGISTRY

/** Total count of testable ATID assertions (sanity check for CI). */
export const ATID_COUNT = Object.keys(ATID_REGISTRY).length

/** All ATID keys grouped by feature, for test-suite organisation. */
export const ATID_BY_FEATURE: Record<AtidEntry['feature'], readonly string[]> = {
  identity: Object.entries(ATID_REGISTRY)
    .filter(([, e]) => e.feature === 'identity')
    .map(([k]) => k),
  complaint: Object.entries(ATID_REGISTRY)
    .filter(([, e]) => e.feature === 'complaint')
    .map(([k]) => k),
  comment: Object.entries(ATID_REGISTRY)
    .filter(([, e]) => e.feature === 'comment')
    .map(([k]) => k),
  discovery: Object.entries(ATID_REGISTRY)
    .filter(([, e]) => e.feature === 'discovery')
    .map(([k]) => k),
  moderation: Object.entries(ATID_REGISTRY)
    .filter(([, e]) => e.feature === 'moderation')
    .map(([k]) => k),
  legal: Object.entries(ATID_REGISTRY)
    .filter(([, e]) => e.feature === 'legal')
    .map(([k]) => k),
  admin: Object.entries(ATID_REGISTRY)
    .filter(([, e]) => e.feature === 'admin')
    .map(([k]) => k),
}
